/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Donation } from "./Donation";
import { DonationCountArgs } from "./DonationCountArgs";
import { DonationFindManyArgs } from "./DonationFindManyArgs";
import { DonationFindUniqueArgs } from "./DonationFindUniqueArgs";
import { DeleteDonationArgs } from "./DeleteDonationArgs";
import { DonationService } from "../donation.service";
@graphql.Resolver(() => Donation)
export class DonationResolverBase {
  constructor(protected readonly service: DonationService) {}

  async _donationsMeta(
    @graphql.Args() args: DonationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Donation])
  async donations(
    @graphql.Args() args: DonationFindManyArgs
  ): Promise<Donation[]> {
    return this.service.donations(args);
  }

  @graphql.Query(() => Donation, { nullable: true })
  async donation(
    @graphql.Args() args: DonationFindUniqueArgs
  ): Promise<Donation | null> {
    const result = await this.service.donation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Donation)
  async deleteDonation(
    @graphql.Args() args: DeleteDonationArgs
  ): Promise<Donation | null> {
    try {
      return await this.service.deleteDonation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
