/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ContactUs } from "./ContactUs";
import { ContactUsCountArgs } from "./ContactUsCountArgs";
import { ContactUsFindManyArgs } from "./ContactUsFindManyArgs";
import { ContactUsFindUniqueArgs } from "./ContactUsFindUniqueArgs";
import { DeleteContactUsArgs } from "./DeleteContactUsArgs";
import { ContactUsService } from "../contactUs.service";
@graphql.Resolver(() => ContactUs)
export class ContactUsResolverBase {
  constructor(protected readonly service: ContactUsService) {}

  async _contactusesMeta(
    @graphql.Args() args: ContactUsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ContactUs])
  async contactuses(
    @graphql.Args() args: ContactUsFindManyArgs
  ): Promise<ContactUs[]> {
    return this.service.contactuses(args);
  }

  @graphql.Query(() => ContactUs, { nullable: true })
  async contactUs(
    @graphql.Args() args: ContactUsFindUniqueArgs
  ): Promise<ContactUs | null> {
    const result = await this.service.contactUs(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ContactUs)
  async deleteContactUs(
    @graphql.Args() args: DeleteContactUsArgs
  ): Promise<ContactUs | null> {
    try {
      return await this.service.deleteContactUs(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
